spring.application.name=veva-jewels

# Server configuration
server.port=port_number_here
server.ssl.enabled=false
# MongoDB configuration
spring.data.mongodb.uri=your_mongodb_uri_here
#spring.data.mongodb.database=Users
spring.data.mongodb.auto-creation=true


# Logging level for better visibility
logging.level.org.springframework.data.mongodb=DEBUG
logging.level.org.mongodb.driver=DEBUG
logging.level.org.springframework.security=DEBUG


# Optional: Enable detailed error messages
server.error.include-message=always

# Enable Swagger/OpenAPI
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

# Optional: Set custom paths for Swagger UI and API docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs

# CORS configuration
spring.web.cors.allowed-origins=http://localhost:3000
spring.web.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.web.cors.allowed-headers=*
spring.web.cors.allow-credentials=true

twilio.account_sid=your_account_sid_here
twilio.auth_token=your_auth_token_here
twilio.service_id=your_service_id_here
jwt.secret=your_jwt_secret_here
